// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-H8MqhV-8GLjV22xWpCznkA1MERYHfjs',
    appId: '1:377259467324:web:eaf020283f78c44c479939',
    messagingSenderId: '377259467324',
    projectId: 'tusharboard-1bf20',
    authDomain: 'tusharboard-1bf20.firebaseapp.com',
    storageBucket: 'tusharboard-1bf20.appspot.com',
    measurementId: 'G-5J5ZN04XR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTo5u2FhF0PtiF8_Ej2WTPTYxxDMuZiMY',
    appId: '1:377259467324:android:968da10bf7635e57479939',
    messagingSenderId: '377259467324',
    projectId: 'tusharboard-1bf20',
    storageBucket: 'tusharboard-1bf20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4SQmxV3avrl5AJi8YQigfdqNPlc48DM',
    appId: '1:377259467324:ios:55b255318cf7db8b479939',
    messagingSenderId: '377259467324',
    projectId: 'tusharboard-1bf20',
    storageBucket: 'tusharboard-1bf20.appspot.com',
    iosBundleId: 'com.example.tusharDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS4SQmxV3avrl5AJi8YQigfdqNPlc48DM',
    appId: '1:377259467324:ios:55b255318cf7db8b479939',
    messagingSenderId: '377259467324',
    projectId: 'tusharboard-1bf20',
    storageBucket: 'tusharboard-1bf20.appspot.com',
    iosBundleId: 'com.example.tusharDb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-H8MqhV-8GLjV22xWpCznkA1MERYHfjs',
    appId: '1:377259467324:web:122f63795e597e8d479939',
    messagingSenderId: '377259467324',
    projectId: 'tusharboard-1bf20',
    authDomain: 'tusharboard-1bf20.firebaseapp.com',
    storageBucket: 'tusharboard-1bf20.appspot.com',
    measurementId: 'G-QF2THWYLHC',
  );
}
